import subprocess
import shlex

def execute_command(command: str) -> dict:
    """
    Executes a system command and returns the output.
    """
    try:
        # Split command for safety (avoid shell=True if possible, but for complex pipes we might need it)
        # Requirement says "translating intent into safe, executable system commands"
        # We will use shell=True to support pipes and standard shell syntax as generated by LLM
        # strictly relying on the 'safety' module to gate destructive commands.
        
        result = subprocess.run(
            command,
            shell=True,
            capture_output=True,
            text=True,
            timeout=30
        )
        
        return {
            "success": result.returncode == 0,
            "stdout": result.stdout.strip(),
            "stderr": result.stderr.strip(),
            "returncode": result.returncode
        }
        
    except subprocess.TimeoutExpired:
        return {
            "success": False,
            "stdout": "",
            "stderr": "Command timed out after 30 seconds.",
            "returncode": -1
        }
    except Exception as e:
        return {
            "success": False,
            "stdout": "",
            "stderr": str(e),
            "returncode": -1
        }

